production: retrain
monai_dataset_dir: /home/aoi/monai/monai-dataset
train_data_dir: /home/aoi/monai/train_data
val_data_dir: /home/aoi/monai/val_data
test_data_dir: /home/aoi/monai/test_data
models_dir: /home/aoi/monai/models
old_model_dir: null
organ_list: null
organ_to_mmar:
  liver:
    name: clara_pt_liver_and_tumor_ct_segmentation_1
    channel: 3
    mmar_dir: /home/aoi/monai/models/mmar/liver
    old_model_dir: null
    old_model_file_path: null
    old_model_dice: null
    new_model_dir: null
    new_model_file_path: null
    new_model_dice: null
  pancreas:
    name: clara_pt_pancreas_and_tumor_ct_segmentation_1
    channel: 3
    mmar_dir: /home/aoi/monai/models/mmar/pancreas
    old_model_dir: null
    old_model_file_path: null
    old_model_dice: null
    new_model_dir: null
    new_model_file_path: null
    new_model_dice: null
  spleen:
    name: clara_pt_spleen_ct_segmentation_1
    channel: 2
    mmar_dir: /home/aoi/monai/models/mmar/spleen
    old_model_dir: null
    old_model_file_path: null
    old_model_dice: null
    new_model_dir: null
    new_model_file_path: null
    new_model_dice: null
roi_size:
- 256
- 256
- 16
scale_min: -135
scale_max: 215
